name: "Test FIPS"
on:
  workflow_dispatch:

jobs:
  test-fips:
    uses: ./.github/workflows/enable-pro.yml
    with:
      workload: 'ls || [[ $? -eq 129 ]]'
    secrets:
      UBUNTU_PRO_TOKEN: ${{ secrets.PRO_TOKEN }}