name: "Validate OpenSSL FIPS mode in LXD VM"
on:
  push:

jobs:
  validate-fips:
    uses: ./.github/workflows/enable-pro.yml
    with:
      workload: |
        openssl version
        cat /proc/sys/crypto/fips_enabled
        cat /proc/cmdline
    secrets:
      UBUNTU_PRO_TOKEN: ${{ secrets.PRO_TOKEN }}