name: "Test FIPS"
on:
  push:

jobs:
  validate-fips:
    uses: ./.github/workflows/enable-pro.yml
    with:
      workload: |
        openssl version
        cat /proc/sys/crypto/fips_enabled
        pro status --format json
    secrets:
      UBUNTU_PRO_TOKEN: ${{ secrets.PRO_TOKEN }}